# Generated by Django 2.2.22 on 2022-03-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220318_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
